### ISSUE TITLE
Npm warning make stack update fails

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-controller#109]
Npm displays a deprecation warning during stack update. This prevent the update to complete and leave the stack stopped.
```
[Mon, 14 Dec 2015 00:49:46 GMT] - POST /apps/update-stack - - - - ms -  -
info - npm:install:success
info - monitor: update
info - monitor: update
info - monitor: update
error - Error during monitor update: npm WARN deprecated This version of npm lacks support for important features,
(…)


info - controller: update
info - controller: update
info - controller: update
error - Error during controller update: npm WARN deprecated This version of npm lacks support for important features,
(…)

Sending error to client: 
Error: Cannot update stack: Error during controller update: npm WARN deprecated This version of npm lacks support for important features,

    at /usr/lib/node_modules/cozy-controller/build/server/controllers/applications.js:298:19
    at /usr/lib/node_modules/cozy-controller/node_modules/async/lib/async.js:525:46
    at /usr/lib/node_modules/cozy-controller/node_modules/async/lib/async.js:254:17
    at /usr/lib/node_modules/cozy-controller/node_modules/async/lib/async.js:151:21
    at /usr/lib/node_modules/cozy-controller/node_modules/async/lib/async.js:251:21
    at /usr/lib/node_modules/cozy-controller/node_modules/async/lib/async.js:615:34
    at /usr/lib/node_modules/cozy-controller/node_modules/async/lib/async.js:516:25
    at /usr/lib/node_modules/cozy-controller/build/server/controllers/applications.js:47:18
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
```

**Comment by poupotte** [comment]
This issue should now fixed.
