### ISSUE TITLE
"TypeError: Cannot set property 'old' of undefined" on cozy-controller startup

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-controller#59]
When I launch my cozy-controller I have an error:
```
# cozy-controller
info - ### FILE INITIALIZATION ###
info - init: source directory

/usr/lib/node_modules/cozy-controller/build/server/lib/conf.js:38
      data.old = require('/etc/cozy/.controller-backup.json');
               ^
TypeError: Cannot set property 'old' of undefined
    at readFile (/usr/lib/node_modules/cozy-controller/build/server/lib/conf.js:38:16)
    at Object.module.exports.init (/usr/lib/node_modules/cozy-controller/build/server/lib/conf.js:59:10)
    at initialize (/usr/lib/node_modules/cozy-controller/build/server/initialize.js:157:17)
    at Object.module.exports.init (/usr/lib/node_modules/cozy-controller/build/server/initialize.js:173:12)
    at module.exports (/usr/lib/node_modules/cozy-controller/build/server.js:37:10)
    at Object.<anonymous> (/usr/lib/node_modules/cozy-controller/bin/cozy-controller:7:43)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

You can found bellow file content.

/etc/cozy/.controller-backup.json:
```
{
  "npm_registry": false,
  "npm_strict_ssl": false,
  "dir_log": "/usr/local/var/log/cozy",
  "dir_source": "/usr/local/cozy/apps",
  "env": {
    "global": false,
    "data-system": false,
    "home": {
      "MARKET": "private"
    },
    "proxy": false
  }
}

And an empty /etc/cozy/controller.json

**Comment by nledez** [comment]
So, it's a filesystem full come from CouchDB logs.

Don't touch to controller, it's fine to have a strange problem to investigate :)
